### PR TITLE
feat: #WB-1977, add new component dropzone

### PR DESCRIPTION
**Pull request by Headan**
# Description

Ajout d'un nouveau composant Dropzone permettant de glisser/déposer des fichiers dans un encart. 

Ticket : #WB-1977
Link : https://edifice-community.atlassian.net/browse/WB-1977

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Which Package changed?

Please check the name of the package you changed

- [x] Components
- [x] Core
- [ ] Icons
- [ ] Hooks

## Has the documentation changed?

- [x] Storybook

## Type of change

Please check options that are relevant.

- [x] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Headan** [comment]
@ccreusat Si tu passes sur la PR je sais qu'elle n'est pas fini mais c'est juste pour la save. Je ferai les modifications en conséquence sur la description si il y a des changements particulier 😄

**Comment by ccreusat** [comment]
⚠️ @Headan pareil, attention le conflit de CSS => à rewatcher depuis edifice-bootstrap@develop-b2school

**Pull request merged**
